src/web/itemcatalog/models/item.py
from datetime import datetime
from . import db, ma


class Item(db.Model):
    """Model to define Item"""

    __tablename__ = 'items'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(80), nullable=False)
    description = db.Column(db.String(4000))
    category_id = db.Column(db.Integer, db.ForeignKey('category.id'),
                            nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'),
                        nullable=False)
    time_inserted = db.Column(db.DateTime(), default=datetime.utcnow)
    time_updated = db.Column(db.DateTime(), default=datetime.utcnow)


class ItemSchema(ma.ModelSchema):
    """Define marshmallow schema"""
    class Meta:
        model = Item

src/web/itemcatalog/forms/item.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired
from wtforms.ext.sqlalchemy.fields import QuerySelectField
from itemcatalog.models.category import Category


def all_categories():
    return Category.query.order_by(Category.name.asc())


class ItemForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired()])
    description = TextAreaField('Description', validators=[DataRequired()])
    category = QuerySelectField(u'Category',
                                get_label=u"name",
                                query_factory=all_categories,
                                allow_blank=False)
    submit = SubmitField('Post')

src/web/itemcatalog/routes/category.py
from flask import Blueprint, render_template
from itemcatalog.models.category import Category


category = Blueprint('category', __name__)


@category.route('/category/<int:category_id>/')
def items_by_category(category_id):
    """Returns items, category for a specific category"""
    filtered_categories = Category.query.filter_by(id=category_id)
    category = filtered_categories[0]
    return render_template('main.html', title=category.name,
                           categories=filtered_categories,
                           items=category.items)

src/web/itemcatalog/routes/item.py
from flask import (render_template, url_for, request,
                   redirect, Blueprint, abort, flash)
from flask_login import current_user, login_required
from itemcatalog import db
from itemcatalog.models.item import Item
from itemcatalog.forms.item import ItemForm
from sqlalchemy import func

item = Blueprint('item', __name__)


@item.route("/item/create", methods=['GET', 'POST'])
@login_required
def create_item():
    """CREATE Item"""
    form = ItemForm()
    if form.validate_on_submit():
        new_item = Item(name=form.name.data,
                        description=form.description.data,
                        category=form.category.data,
                        user=current_user)
        db.session.add(new_item)
        db.session.commit()
        flash('Your job listing has been successfully created!', 'success')
        return redirect(url_for('main.index'))
    return render_template('item.html', form=form)


@item.route("/item/<int:item_id>/update", methods=['GET', 'POST'])
@login_required
def update_item(item_id):
    """
    UPDATE Item
    :param item_id: item_id (int) for Item
    """
    item = Item.query.get_or_404(item_id)
    if item.user != current_user:
        abort(403)
    form = ItemForm()
    if form.validate_on_submit():
        item.name = form.name.data
        item.description = form.description.data
        item.category = form.category.data
        item.time_updated = func.now()
        db.session.commit()
        flash('Your job listing has been successfully updated!', 'success')
        return redirect(url_for('main.index'))
    elif request.method == 'GET':
        form.name.data = item.name
        form.description.data = item.description
        form.category.data = item.category
    return render_template('item.html', form=form)


@item.route("/item/<int:item_id>/delete", methods=['POST'])
@login_required
def delete_item(item_id):
    """
    DELETE Item
    :param item_id: item_id (int) for Item
    """
    item = Item.query.get_or_404(item_id)
    if item.user != current_user:
        abort(403)
    db.session.delete(item)
    db.session.commit()
    flash('Your job listing has been successfully deleted!', 'success')
    return redirect(url_for('main.index'))

src/web/itemcatalog/routes/main.py
from flask import Blueprint, render_template, jsonify
from itemcatalog.models.category import Category, CategorySchema
from itemcatalog.models.item import Item
from flask_login import current_user


main = Blueprint('main', __name__)


@main.route('/')
@main.route("/home")
def index():
    """Returns all items and categories"""
    categories = Category.query.filter(Category.item_count > 0).order_by(Category.name)  # noqa:501
    items = Item.query.order_by(Item.time_updated.desc())
    return render_template('main.html', title='Home', categories=categories,
                           items=items, current_user=current_user)


@main.route('/api/v1/catalog/json')
def get_catalog():
    """Returns of all categories and nested items in catalog"""
    categories = Category.query.filter(Category.item_count > 0).order_by(Category.name)  # noqa:501
    category_schema = CategorySchema(many=True)
    response = category_schema.dump(categories).data
    return jsonify({'categories': response})

src/web/itemcatalog/routes/userauth.py
from flask import Blueprint, redirect, url_for, session, flash
from flask_dance.contrib.google import make_google_blueprint, google
from flask_dance.consumer.backend.sqla import SQLAlchemyBackend
from flask_login import current_user, login_user, logout_user
from flask_dance.consumer import oauth_authorized
from sqlalchemy.orm.exc import NoResultFound
from oauthlib.oauth2.rfc6749.errors import InvalidClientIdError
from itemcatalog import app, db, user

userauth = Blueprint('userauth', __name__)

app.secret_key = app.config['GOOGLE_OAUTH_CLIENT_SECRET']

google_blueprint = make_google_blueprint(
    client_id=app.config['GOOGLE_OAUTH_CLIENT_ID'],
    client_secret=app.secret_key,
    scope=app.config['GOOGLE_OAUTH_CLIENT_SCOPE'],
    offline=True
    )

google_blueprint.backend = SQLAlchemyBackend(user.UserAuth, db.session,
                                             user=current_user,
                                             user_required=False)

app.register_blueprint(google_blueprint, url_prefix="/google_login")


@userauth.route("/google_login")
def google_login():
    """redirect to Google to initiate oAuth2.0 dance"""
    if not google.authorized:
        return redirect(url_for("google.login"))
    resp = google.get("/oauth2/v2/userinfo")
    assert resp.ok, resp.text
    return resp.text


@oauth_authorized.connect_via(google_blueprint)
def google_logged_in(blueprint, token):
    """
    Receives a signal that Google has authenticated User via
    instance of blueprint and token
        1. Check response from instance of blueprint
        2. Check if user exists from db via email
        3. Create user in db if user does not exist
    """
    from itemcatalog import user
    User = user.User
    resp = blueprint.session.get("/oauth2/v2/userinfo")
    if resp.ok:
        account_info_json = resp.json()
        email = account_info_json['email']
        query = User.query.filter_by(email=email)

        try:
            user = query.one()
        except NoResultFound:
            user = User()
            user.name = account_info_json['name']
            user.email = account_info_json['email']
            db.session.add(user)
            db.session.commit()
        login_user(user, remember=True)


@userauth.route('/google_logout')
def google_logout():
    """Revokes token and empties session."""
    if google.authorized:
        try:
            google.get(
                'https://accounts.google.com/o/oauth2/revoke',
                params={
                    'token':
                    google.token['access_token']},
            )
        except InvalidClientIdError:
            """Revokes token and empties session."""
            del google.token
            redirect(url_for('main.index'))
    session.clear()
    logout_user()
    flash('You have been logged out!', 'success')
    return redirect(url_for('main.index'))

src/web/itemcatalog/templates/item.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Post Item</legend>
            <div class="form-group">
                {{ form.name.label(class="form-control-label") }}
                {% if form.name.errors %}
                {{ form.name(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.name.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.name(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.description.label(class="form-control-label") }}
                {% if form.description.errors %}
                {{ form.description(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.description.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.description(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.category.label(class="form-control-label") }}
                {% if form.category.errors %}
                {{ form.category(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.category.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.category(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>
{% endblock content %}

src/web/itemcatalog/templates/layout.html
<!DOCTYPE html>
<html>

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="google" content="notranslate">
  <meta http-equiv="Content-Language" content="en">
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
    crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles/main.css') }}">
  <title>Jobs</title>
</head>

<body>
  <header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
      <div class="container">
        <a class="navbar-brand mr-4" href="/">Jobs</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle"
          aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarToggle">
          <div class="navbar-nav mr-auto">
            <a class="nav-item nav-link" href="{{ url_for('main.index') }}">All Jobs</a>
            {% if current_user.is_authenticated %}
            <a class="nav-item nav-link" href="{{ url_for('item.create_item') }}">Post New Job</a>
            {% endif %}
          </div>
          <!-- Navbar Right Side -->
          <div class="navbar-nav">
            {% if current_user.is_authenticated %}
            <a class="nav-item nav-link" href="{{ url_for('userauth.google_logout') }}">Logout {{ current_user.name }}</a>
            {% else %}
            <a href="{{ url_for('google.login') }}" class="navbar-left"><img src="{{ url_for('static', filename='img/google.png') }}"></a>
            {% endif %}
          </div>
        </div>
      </div>
    </nav>
  </header>
  <main role="main" class="container">
    <div class="row">
      <div class="col-md-12">
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        {% for category, message in messages %}
        <div class="alert alert-{{ category }}">
          {{ message }}
        </div>
        {% endfor %}
        {% endif %}
        {% endwith %}
        {% block content %}{% endblock %}
      </div>
    </div>
  </main>
  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>
</body>

</html>

src/web/itemcatalog/templates/main.html
{% extends "layout.html" %}
{% block content %}
<div class="row">
    <div class="col-md-4">
        <div class="content-section" align="center">
            <h3>State</h3>
            <br>
            <ul class="list-group">
                {% for category in categories %}
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    <a href="{{ url_for('category.items_by_category', category_id=category.id) }}">{{ category.name }}</a>
                    <span class="badge badge-primary badge-pill">{{ category.item_count }}</span>
                </li>
                {% endfor %}
            </ul>
            <br>
        </div>
    </div>
    <div class="col-md-8">
        <div class="content-section">
            <h3>
                <div style="text-align: center">Jobs</div>
            </h3><br>
            {% for item in items %}
            <article class="media content-section">
                <div class="media-body">
                    <div class="article-metadata">
                        <a class="mr-3">
                            <span style="float: left" href="#"><b>{{item.name}}</b></span>
                            <span style="float: right"><small>{{ item.category.name }}</small></span>
                        </a>
                    </div>
                    <p class="article-content"><small>{{ item.description }}</small></p>

                    <footer>
                        <span style="float: left"><small>
                                <p>
                                    Posted on
                                    {{ item.time_updated.strftime('%A %B %d, %Y') }}
                                    by <b>{{ item.user.name }}</b>.
                                </p>
                            </small></span>
                        {% if item.user == current_user %}
                        <span style="float: right">
                            <a href="{{ url_for('item.update_item', item_id=item.id) }}"><button type="button" class="btn btn-primary btn-sm">Update</button></a>
                            <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#deleteModal">Delete</button>
                        </span>
                        {% endif %}
                    </footer>
                </div>
            </article>
            <!-- Modal -->
            <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
                aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="deleteModalLabel">Delete {{ item.name }}?</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            <form action="{{ url_for('item.delete_item', item_id=item.id) }}" method="POST">
                                <input class="btn btn-danger" type="submit" value="Delete">
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>

</div>

{% endblock content %}